"""Les schémas SVG disponibles, vus depuis le serveur — FICHIER GÉNÉRÉ.

Ne pas éditer à la main : lancer `python tools/generate_schema_catalog.py`
après avoir ajouté un schéma dans
`frontend/src/components/session/schemas/schemas_*.ts`.

Le catalogue sert au prompt : un identifiant absent d'ici n'existe pas pour le
modèle, et un schéma que personne ne nomme ne s'affiche jamais.
"""

from __future__ import annotations

import re
import unicodedata
from functools import lru_cache

SCHEMA_CATALOG: list[dict] = [
    {"id": 'chem_cinetique', "title": 'Transformations lentes et rapides — facteurs cinétiques', "subject": 'chemistry', "keywords": ['cinétique', 'vitesse', 'réaction', 'concentration', 'temps demi-réaction', 'avancement', 'transformations lentes', 'transformations rapides', 'suivi temporel', 'سرعة التفاعل', 'حركية كيميائية', 'facteurs cinétiques'], "metadata": {}},
    {"id": 'chem_radioactivite', "title": 'Radioactivité — Décroissance radioactive', "subject": 'chemistry', "keywords": ['radioactivité', 'décroissance', 'demi-vie', 'alpha', 'beta', 'gamma', 'noyau', 'نشاط إشعاعي', 'عمر النصف', 'تفكك'], "metadata": {}},
    {"id": 'chem_acides_bases', "title": 'Acides et bases — Équilibres en solution aqueuse', "subject": 'chemistry', "keywords": ['acide', 'base', 'pH', 'Ka', 'pKa', 'tampon', 'titrage', 'dosage', 'حمض', 'قاعدة', 'معايرة', 'équilibre'], "metadata": {}},
    {"id": 'chem_piles_electrolyse', "title": 'Piles électrochimiques et électrolyse', "subject": 'chemistry', "keywords": ['pile', 'électrolyse', 'anode', 'cathode', 'oxydation', 'réduction', 'fem', 'galvani', 'عمود كهروكيميائي', 'تحليل كهربائي', 'قطب'], "metadata": {}},
    {"id": 'chem_esterification', "title": 'Estérification et hydrolyse', "subject": 'chemistry', "keywords": ['ester', 'estérification', 'hydrolyse', 'acide carboxylique', 'alcool', 'rendement', 'catalyse', 'أسترة', 'حلمأة', 'كيمياء عضوية'], "metadata": {}},
    {"id": 'chem_croquis_carte_cinetique', "title": 'Croquis au crayon — Carte des transformations rapides et lentes', "subject": 'chemistry', "keywords": ['transformation rapide lente', 'cinétique chimique', 'durée transformation', 'facteurs cinétiques', 'concentration température'], "metadata": {'courseId': 'chem_ch1_kinetics', 'chapter': 'Transformations lentes et transformations rapides', 'lesson': 'Durée et facteurs cinétiques', 'visualStyle': 'pencil', 'resourceRole': 'teacher_sketch', 'paletteId': 'bac-pencil-v1', 'sourceUrl': 'https://www.youtube.com/watch?v=WAHItI0S14A', 'sourceTeacher': 'Zakaria TAOUSSE', 'sourceVideoTitle': 'leçon 01 chimie BIOF - Les transformation rapides et lentes', 'auditStatus': 'video_reviewed', 'sourceTimecodes': ['00:35–02:10 · carte du cours : rapide, lente, concentration et température'], 'learningObjectives': ['Organiser les notions du premier cours de cinétique', 'Distinguer classement temporel et facteurs expérimentaux'], 'llmIntents': ['dessiner la carte rapide lente', 'résumer les facteurs cinétiques du cours'], 'drawingSteps': ['Écrire transformation chimique au centre', 'Créer les branches rapide et lente', 'Ajouter la durée d’observation', 'Ajouter concentration et température comme facteurs']}},
    {"id": 'chem_croquis_transfert_electrons', "title": 'Croquis au crayon — Transfert d’électrons en oxydoréduction', "subject": 'chemistry', "keywords": ['oxydoréduction', 'oxydant réducteur', 'transfert électrons', 'demi équation électronique', 'couple ox red'], "metadata": {'courseId': 'chem_ch1_kinetics', 'chapter': 'Transformations lentes et transformations rapides', 'lesson': 'Rappel : réactions d’oxydoréduction', 'visualStyle': 'pencil', 'resourceRole': 'teacher_sketch', 'paletteId': 'bac-pencil-v1', 'sourceUrl': 'https://www.youtube.com/watch?v=WAHItI0S14A', 'sourceTeacher': 'Zakaria TAOUSSE', 'sourceVideoTitle': 'leçon 01 chimie BIOF - Les transformation rapides et lentes', 'auditStatus': 'video_reviewed', 'sourceTimecodes': ['02:30–09:30 · oxydant, réducteur, couples et transfert des électrons'], 'learningObjectives': ['Identifier donneur et accepteur d’électrons', 'Assembler deux demi-équations sans laisser d’électrons dans le bilan'], 'llmIntents': ['dessiner le transfert d’électrons', 'rappeler oxydant et réducteur avant la cinétique'], 'drawingSteps': ['Placer le réducteur à gauche', 'Tracer les électrons vers l’oxydant', 'Écrire les deux demi-équations', 'Barrer les électrons dans le bilan final']}},
    {"id": 'chem_croquis_duree_transformation', "title": 'Croquis au crayon — Durée d’une transformation chimique', "subject": 'chemistry', "keywords": ['durée transformation', 'transformation rapide lente', 'avancement temps plateau', 'courbe cinétique', 'instantanée'], "metadata": {'courseId': 'chem_ch1_kinetics', 'chapter': 'Transformations lentes et transformations rapides', 'lesson': 'Durée et facteurs cinétiques', 'visualStyle': 'pencil', 'resourceRole': 'teacher_sketch', 'paletteId': 'bac-pencil-v1', 'sourceUrl': 'https://www.youtube.com/watch?v=WAHItI0S14A', 'sourceTeacher': 'Zakaria TAOUSSE', 'sourceVideoTitle': 'leçon 01 chimie BIOF - Les transformation rapides et lentes', 'auditStatus': 'video_reviewed', 'sourceTimecodes': ['23:50–26:40 · courbe d’évolution, plateau et durée Δt'], 'learningObjectives': ['Lire la durée d’une transformation sur une courbe', 'Classer rapide et lente relativement au moyen d’observation'], 'llmIntents': ['dessiner une courbe cinétique vers un plateau', 'expliquer la durée delta t'], 'drawingSteps': ['Tracer les axes t et x', 'Dessiner une croissance vers un plateau', 'Projeter la fin sur l’axe du temps', 'Comparer à la durée d’observation']}},
    {"id": 'chem_croquis_facteurs_controles', "title": 'Croquis au crayon — Comparer concentration et température', "subject": 'chemistry', "keywords": ['facteurs cinétiques expérience', 'concentration température', 'deux béchers comparaison', 'essai témoin', 'variables contrôlées'], "metadata": {'courseId': 'chem_ch1_kinetics', 'chapter': 'Transformations lentes et transformations rapides', 'lesson': 'Durée et facteurs cinétiques', 'visualStyle': 'pencil', 'resourceRole': 'teacher_sketch', 'paletteId': 'bac-pencil-v1', 'sourceUrl': 'https://www.youtube.com/watch?v=WAHItI0S14A', 'sourceTeacher': 'Zakaria TAOUSSE', 'sourceVideoTitle': 'leçon 01 chimie BIOF - Les transformation rapides et lentes', 'auditStatus': 'video_reviewed', 'sourceTimecodes': ['27:00–31:20 · comparaison de béchers à concentration ou température différente'], 'learningObjectives': ['Construire une comparaison où une seule variable change', 'Prévoir l’effet d’une concentration ou température plus élevée'], 'llmIntents': ['dessiner deux béchers pour comparer la température', 'dessiner une expérience sur la concentration'], 'drawingSteps': ['Tracer deux béchers identiques', 'Écrire ce qui reste identique', 'Colorer la seule variable manipulée', 'Indiquer la transformation la plus rapide']}},
    {"id": 'chem_croquis_trois_bechers', "title": 'Croquis au crayon — Trois béchers à températures différentes', "subject": 'chemistry', "keywords": ['trois béchers température', 'dégagement gazeux température', 'bulles réaction froide chaude', 'diagnostic cinétique'], "metadata": {'courseId': 'chem_ch1_kinetics', 'chapter': 'Transformations lentes et transformations rapides', 'lesson': 'Diagnostic — mêmes réactifs, durées différentes', 'visualStyle': 'pencil', 'resourceRole': 'teacher_sketch', 'paletteId': 'bac-pencil-v1', 'auditStatus': 'curriculum_reviewed', 'learningObjectives': ['Comparer qualitativement la rapidité dans trois conditions', 'Formuler l’hypothèse que la température est un facteur cinétique'], 'llmIntents': ['dessiner trois béchers froid tempéré chaud', 'faire prédire l’intensité du dégagement gazeux'], 'drawingSteps': ['Tracer trois béchers identiques', 'Ajouter les mêmes réactifs', 'Noter les trois températures', 'Dessiner peu, moyen puis beaucoup de bulles', 'Formuler l’hypothèse']}},
    {"id": 'chem_croquis_indices_macroscopiques', "title": 'Croquis au crayon — Indices macroscopiques d’une transformation', "subject": 'chemistry', "keywords": ['indice macroscopique transformation', 'couleur absorbance gaz pression pH conductivité', 'suivi cinétique grandeur mesurable', 'précipité'], "metadata": {'courseId': 'chem_ch1_kinetics', 'chapter': 'Transformations lentes et transformations rapides', 'lesson': 'Classer — rapide ou lente à l’échelle de l’observation', 'visualStyle': 'pencil', 'resourceRole': 'teacher_sketch', 'paletteId': 'bac-pencil-v1', 'auditStatus': 'curriculum_reviewed', 'learningObjectives': ['Choisir une grandeur mesurable liée à l’avancement', 'Distinguer observation qualitative et suivi quantitatif'], 'llmIntents': ['dessiner les indices d’une transformation chimique', 'choisir entre couleur gaz pH et conductivité'], 'drawingSteps': ['Tracer quatre vignettes', 'Dessiner changement de couleur', 'Dessiner gaz ou pression', 'Dessiner pH/conductivité', 'Relier chaque indice à une grandeur suivie']}},
    {"id": 'chem_croquis_quatre_facteurs', "title": 'Croquis au crayon — Les quatre facteurs cinétiques', "subject": 'chemistry', "keywords": ['quatre facteurs cinétiques', 'température concentration surface catalyseur', 'chocs efficaces', 'accélérer transformation', 'carte facteurs'], "metadata": {'courseId': 'chem_ch1_kinetics', 'chapter': 'Transformations lentes et transformations rapides', 'lesson': 'Facteurs cinétiques — accélérer sans changer le bilan', 'visualStyle': 'pencil', 'resourceRole': 'teacher_sketch', 'paletteId': 'bac-pencil-v1', 'auditStatus': 'curriculum_reviewed', 'learningObjectives': ['Relier chaque facteur à un mécanisme microscopique', 'Séparer rapidité et état final'], 'llmIntents': ['dessiner les quatre facteurs cinétiques', 'expliquer chocs fréquents surface et catalyse'], 'drawingSteps': ['Écrire rapidité au centre', 'Ajouter température et concentration', 'Ajouter surface de contact et catalyseur', 'Relier aux chocs efficaces ou à une voie facilitée', 'Préciser que le bilan final ne change pas']}},
    {"id": 'chem_croquis_catalyseur', "title": 'Croquis au crayon — Ce que change un catalyseur', "subject": 'chemistry', "keywords": ['catalyseur énergie activation', 'profil énergie activation', 'profil énergétique catalysé', 'catalyseur régénéré', 'même état final', 'voie réactionnelle'], "metadata": {'courseId': 'chem_ch1_kinetics', 'chapter': 'Transformations lentes et transformations rapides', 'lesson': 'Le catalyseur : trois idées à ne pas confondre', 'visualStyle': 'pencil', 'resourceRole': 'teacher_sketch', 'paletteId': 'bac-pencil-v1', 'auditStatus': 'curriculum_reviewed', 'learningObjectives': ['Expliquer l’accélération par une voie d’activation plus basse', 'Montrer que le catalyseur est régénéré et ne change pas l’état final'], 'llmIntents': ['dessiner le profil énergétique avec et sans catalyseur', 'expliquer catalyseur régénéré et même quantité finale'], 'drawingSteps': ['Tracer énergie en fonction de l’avancement', 'Placer mêmes niveaux initial et final', 'Dessiner la barrière haute sans catalyseur', 'Dessiner la barrière basse catalysée', 'Ajouter Cat au départ et régénéré à la fin']}},
    {"id": 'chem_croquis_surface_contact', "title": 'Croquis au crayon — Comprimé entier ou réduit en poudre', "subject": 'chemistry', "keywords": ['surface de contact', 'comprimé entier poudre', 'même masse solide', 'facteur cinétique solide', 'protocole surface'], "metadata": {'courseId': 'chem_ch1_kinetics', 'chapter': 'Transformations lentes et transformations rapides', 'lesson': 'Méthode BAC — proposer et critiquer un protocole', 'visualStyle': 'pencil', 'resourceRole': 'teacher_sketch', 'paletteId': 'bac-pencil-v1', 'auditStatus': 'curriculum_reviewed', 'learningObjectives': ['Proposer un protocole contrôlé sur la surface de contact', 'Relier poudre et nombre de sites accessibles'], 'llmIntents': ['dessiner comprimé entier contre poudre', 'expliquer l’effet de la surface de contact'], 'drawingSteps': ['Tracer deux béchers identiques', 'Placer la même masse sous deux formes', 'Indiquer les paramètres constants', 'Montrer davantage de bulles avec la poudre', 'Conclure surface plus grande donc plus rapide']}},
    {"id": 'chem_croquis_courbes_facteur', "title": 'Croquis au crayon — Deux cinétiques, même état final', "subject": 'chemistry', "keywords": ['deux courbes cinétiques', 'pente initiale durée demi réaction', 'même plateau facteur cinétique', 'plus rapide courbe', 'avancement temps comparaison'], "metadata": {'courseId': 'chem_ch1_kinetics', 'chapter': 'Transformations lentes et transformations rapides', 'lesson': 'Laboratoire — isoler l’effet d’un facteur', 'visualStyle': 'pencil', 'resourceRole': 'teacher_sketch', 'paletteId': 'bac-pencil-v1', 'auditStatus': 'curriculum_reviewed', 'learningObjectives': ['Comparer pentes initiales et durées caractéristiques', 'Conclure qu’un facteur cinétique accélère sans modifier le plateau'], 'llmIntents': ['dessiner deux courbes rapide et lente', 'expliquer même état final mais durées différentes'], 'drawingSteps': ['Tracer x en fonction de t', 'Placer le plateau commun xf', 'Dessiner la courbe témoin', 'Dessiner la courbe accélérée plus raide', 'Comparer t1/2 et l’état final']}},
    {"id": 'math_limites', "title": 'Limites et continuité — méthodes du BAC', "subject": 'math', "keywords": ['limite', 'continuité', 'asymptote', 'infini', 'indétermination', 'théorème', 'نهاية', 'دالة', 'استمرارية'], "metadata": {}},
    {"id": 'math_derivation', "title": 'Dérivation — Tableau de dérivées et applications', "subject": 'math', "keywords": ['dérivée', 'dérivation', 'tangente', 'variation', 'tableau', 'extremum', 'مشتقة', 'اشتقاق', 'دراسة دالة'], "metadata": {}},
    {"id": 'math_exp_ln', "title": 'Fonctions exponentielle et logarithme', "subject": 'math', "keywords": ['exponentielle', 'logarithme', 'ln', 'exp', 'croissance', 'décroissance', 'أسية', 'لوغاريتم'], "metadata": {}},
    {"id": 'math_suites', "title": 'Suites numériques — Arithmétiques et géométriques', "subject": 'math', "keywords": ['suite', 'arithmétique', 'géométrique', 'convergence', 'raison', 'terme général', 'somme', 'متتالية', 'حسابية', 'هندسية'], "metadata": {}},
    {"id": 'math_integrales', "title": "Intégration — Primitives et calcul d'aires", "subject": 'math', "keywords": ['intégrale', 'calcul intégral', 'primitive', 'aire sous la courbe', 'intégration', 'intégration par parties', 'تكامل', 'مساحة', 'دالة أصلية'], "metadata": {}},
    {"id": 'math_probabilites', "title": 'Probabilités — Lois et dénombrement', "subject": 'math', "keywords": ['probabilité', 'dénombrement', 'combinaison', 'arrangement', 'bernoulli', 'binomiale', 'variable aléatoire', 'espérance', 'احتمال', 'توزيع', 'ثنائي الحدين'], "metadata": {}},
    {"id": 'math_croquis_formes_indeterminees', "title": 'Croquis au crayon — Les quatre formes indéterminées', "subject": 'math', "keywords": ['formes indéterminées', 'FI limites', 'zéro sur zéro', 'infini sur infini', 'zéro fois infini', 'infini moins infini'], "metadata": {'courseId': 'math_ch1_limits', 'chapter': 'Limites et continuité', 'lesson': 'Lever une forme indéterminée', 'visualStyle': 'pencil', 'resourceRole': 'teacher_sketch', 'paletteId': 'bac-pencil-v1', 'sourceUrl': 'https://www.youtube.com/watch?v=rhN5zNtTiuE', 'sourceTeacher': 'Mouad Tahiri', 'sourceVideoTitle': 'Séance N°1 : Les limites - 2bac astuces et méthode', 'auditStatus': 'video_reviewed', 'sourceTimecodes': ['04:20–06:00 · rappel au tableau des quatre formes indéterminées'], 'learningObjectives': ['Reconnaître une forme indéterminée sans lui attribuer une valeur', 'Choisir ensuite une transformation algébrique adaptée'], 'llmIntents': ['dessiner la carte des formes indéterminées', 'rappeler les quatre FI en limites'], 'drawingSteps': ['Écrire FI au centre', 'Dessiner quatre bulles', 'Placer 0/0, ∞/∞, 0×∞ et ∞−∞', 'Ajouter l’avertissement : ce n’est pas un résultat']}},
    {"id": 'math_croquis_boite_factorisation', "title": 'Croquis au crayon — Boîte à outils de factorisation', "subject": 'math', "keywords": ['factorisation limite', 'identités remarquables', 'a carré moins b carré', 'a cube moins b cube', 'racine polynôme', 'lever 0 sur 0'], "metadata": {'courseId': 'math_ch1_limits', 'chapter': 'Limites et continuité', 'lesson': 'Lever une forme indéterminée', 'visualStyle': 'pencil', 'resourceRole': 'teacher_sketch', 'paletteId': 'bac-pencil-v1', 'sourceUrl': 'https://www.youtube.com/watch?v=rhN5zNtTiuE', 'sourceTeacher': 'Mouad Tahiri', 'sourceVideoTitle': 'Séance N°1 : Les limites - 2bac astuces et méthode', 'auditStatus': 'video_reviewed', 'sourceTimecodes': ['04:30–11:00 · identités remarquables et factorisation', '14:30–22:30 · factoriser par x−a lorsque P(a)=0'], 'learningObjectives': ['Choisir une identité remarquable pour factoriser', 'Extraire le facteur x−a d’un polynôme qui s’annule en a'], 'llmIntents': ['dessiner la boîte des identités remarquables', 'montrer les factorisations utiles pour une limite'], 'drawingSteps': ['Tracer une boîte d’outils', 'Écrire le facteur commun', 'Ajouter les identités de degré deux et trois', 'Relier P(a)=0 à la présence du facteur x−a']}},
    {"id": 'math_croquis_strategie_fi', "title": 'Croquis au crayon — Stratégie pour lever 0/0', "subject": 'math', "keywords": ['méthode limite 0 sur 0', 'stratégie forme indéterminée', 'substitution factorisation simplification', 'limite quotient polynômes', 'x carré moins 4'], "metadata": {'courseId': 'math_ch1_limits', 'chapter': 'Limites et continuité', 'lesson': 'Lever une forme indéterminée', 'visualStyle': 'pencil', 'resourceRole': 'teacher_sketch', 'paletteId': 'bac-pencil-v1', 'sourceUrl': 'https://www.youtube.com/watch?v=rhN5zNtTiuE', 'sourceTeacher': 'Mouad Tahiri', 'sourceVideoTitle': 'Séance N°1 : Les limites - 2bac astuces et méthode', 'auditStatus': 'video_reviewed', 'sourceTimecodes': ['05:00–08:30 · exemple (x²−4)/(3x−6)', '12:00–22:30 · méthode répétée sur des polynômes de degré supérieur'], 'learningObjectives': ['Structurer la résolution d’une limite donnant 0/0', 'Justifier la factorisation puis la simplification au voisinage du point'], 'llmIntents': ['dessiner l’algorithme pour lever zéro sur zéro', 'résoudre graphiquement la méthode factoriser simplifier remplacer'], 'drawingSteps': ['Remplacer x par a', 'Identifier 0/0', 'Factoriser numérateur et dénominateur', 'Simplifier le facteur x−a', 'Remplacer de nouveau et conclure']}},
    {"id": 'math_croquis_trou_limite', "title": 'Croquis au crayon — Un trou, mais une limite finie', "subject": 'math', "keywords": ['trou dans la courbe', 'limite finie fonction non définie', 'x carré moins 1 sur x moins 1', 'limite en 1 égale 2', 'prolongement par continuité'], "metadata": {'courseId': 'math_ch1_limits', 'chapter': 'Limites et continuité', 'lesson': 'Calculer — reconnaître puis lever une indétermination', 'visualStyle': 'pencil', 'resourceRole': 'teacher_sketch', 'paletteId': 'bac-pencil-v1', 'auditStatus': 'curriculum_reviewed', 'learningObjectives': ['Distinguer valeur f(a) et limite quand x tend vers a', 'Interpréter une simplification valable au voisinage de a'], 'llmIntents': ['dessiner une droite avec un trou', 'expliquer pourquoi la limite existe même si f de a n’existe pas'], 'drawingSteps': ['Tracer les axes et la droite y=x+1', 'Effacer le point de la courbe en (1,2)', 'Faire approcher deux flèches de gauche et de droite', 'Écrire f non définie en 1 mais limite égale 2']}},
    {"id": 'math_croquis_asymptotes', "title": 'Croquis au crayon — Asymptotes verticale et horizontale', "subject": 'math', "keywords": ['asymptote verticale horizontale', 'limite infinie en a', 'limite finie à infini', 'x égale a y égale L', 'fonction 1 sur x'], "metadata": {'courseId': 'math_ch1_limits', 'chapter': 'Limites et continuité', 'lesson': 'Asymptotes — traduire une limite en géométrie', 'visualStyle': 'pencil', 'resourceRole': 'teacher_sketch', 'paletteId': 'bac-pencil-v1', 'auditStatus': 'curriculum_reviewed', 'learningObjectives': ['Associer chaque type de limite à l’équation correcte de l’asymptote', 'Lire les comportements unilatéraux près d’une asymptote verticale'], 'llmIntents': ['dessiner asymptote verticale et horizontale', 'expliquer x égale a contre y égale L'], 'drawingSteps': ['Tracer le repère', 'Dessiner x=a en pointillés', 'Dessiner y=L en pointillés', 'Tracer deux branches qui s’en approchent', 'Écrire les limites justificatives']}},
    {"id": 'math_croquis_tvi', "title": 'Croquis au crayon — Théorème des valeurs intermédiaires', "subject": 'math', "keywords": ['théorème valeurs intermédiaires', 'TVI solution f x égale zéro', 'continuité intervalle', 'changement de signe', 'existence unicité racine'], "metadata": {'courseId': 'math_ch1_limits', 'chapter': 'Limites et continuité', 'lesson': 'Continuité et TVI — existence puis unicité', 'visualStyle': 'pencil', 'resourceRole': 'teacher_sketch', 'paletteId': 'bac-pencil-v1', 'auditStatus': 'curriculum_reviewed', 'learningObjectives': ['Vérifier les trois hypothèses du TVI', 'Distinguer existence et unicité d’une solution'], 'llmIntents': ['dessiner le TVI avec changement de signe', 'expliquer existence puis unicité d’une racine'], 'drawingSteps': ['Tracer l’intervalle fermé de a à b et une courbe continue', 'Placer f(a) sous 0 et f(b) au-dessus de 0', 'Colorer la bande des valeurs intermédiaires', 'Marquer une intersection α', 'Ajouter la monotonie seulement pour l’unicité']}},
    {"id": 'math_croquis_carte_methodes', "title": 'Croquis au crayon — Carte des méthodes de limites', "subject": 'math', "keywords": ['carte méthodes limites', 'calcul direct factoriser conjugué terme dominant', 'asymptote continuité TVI', 'synthèse limites', 'méthode BAC limites'], "metadata": {'courseId': 'math_ch1_limits', 'chapter': 'Limites et continuité', 'lesson': 'Bilan de compétence', 'visualStyle': 'pencil', 'resourceRole': 'teacher_sketch', 'paletteId': 'bac-pencil-v1', 'auditStatus': 'curriculum_reviewed', 'learningObjectives': ['Choisir une méthode à partir du diagnostic initial', 'Relier calcul de limite, géométrie et preuve d’existence'], 'llmIntents': ['dessiner la carte complète du chapitre limites', 'choisir entre factoriser conjugué dominant asymptote et TVI'], 'drawingSteps': ['Écrire limite au centre', 'Créer la branche calcul direct', 'Créer la branche FI et ses quatre outils', 'Créer la branche interprétation asymptotique', 'Créer la branche continuité et TVI']}},
    {"id": 'phys_ondes_mecaniques', "title": 'Ondes mécaniques progressives — propagation et retard', "subject": 'physics', "keywords": ['onde', 'mécanique', 'progressive', 'perturbation', 'propagation', 'retard', 'célérité', 'transversale', 'longitudinale', 'موجة', 'انتشار'], "metadata": {}},
    {"id": 'phys_dipole_rc', "title": 'Dipôle RC — Charge et décharge', "subject": 'physics', "keywords": ['rc', 'condensateur', 'charge', 'décharge', 'constante temps', 'tau', 'exponentielle', 'مكثف', 'ثنائي القطب'], "metadata": {}},
    {"id": 'phys_rlc', "title": 'Oscillations RLC série', "subject": 'physics', "keywords": ['rlc', 'oscillations', 'libres', 'amorties', 'pseudo-période', 'résonance', 'énergie', 'تذبذبات', 'حرة', 'رنين'], "metadata": {}},
    {"id": 'phys_newton', "title": 'Les trois lois de Newton', "subject": 'physics', "keywords": ['newton', 'lois', 'inertie', 'accélération', 'action réaction', 'force', 'قوانين نيوتن', 'مركز القصور'], "metadata": {}},
    {"id": 'phys_croquis_propagation_locale', "title": 'Croquis au crayon — Propagation et mouvement local', "subject": 'physics', "keywords": ['onde mécanique progressive', 'perturbation corde', 'propagation sans transport de matière', 'mouvement local', 'impulsion'], "metadata": {'courseId': 'phys_ch1_waves', 'chapter': 'Ondes mécaniques progressives', 'lesson': 'Propagation, retard et célérité', 'visualStyle': 'pencil', 'resourceRole': 'teacher_sketch', 'paletteId': 'bac-pencil-v1', 'sourceUrl': 'https://www.youtube.com/watch?v=E79tE5gmdrk', 'sourceTeacher': 'Jihad El Goufifa', 'sourceVideoTitle': 'Physique-Chimie 2Bac - 1: Les ondes mécaniques progressives (Cours)', 'auditStatus': 'video_reviewed', 'sourceTimecodes': ['09:30–12:00 · impulsion sur une corde et directions du mouvement'], 'learningObjectives': ['Distinguer propagation de la perturbation et mouvement local du milieu', 'Montrer l’absence de transport global de matière'], 'llmIntents': ['dessiner une impulsion qui se propage', 'expliquer ce qui bouge dans une onde mécanique'], 'drawingSteps': ['Tracer la position d’équilibre', 'Dessiner l’impulsion à deux dates', 'Ajouter la flèche de propagation', 'Montrer l’oscillation verticale d’un point P']}},
    {"id": 'phys_croquis_transversale_longitudinale', "title": 'Croquis au crayon — Onde transversale ou longitudinale', "subject": 'physics', "keywords": ['onde transversale', 'onde longitudinale', 'corde ressort', 'compression dilatation', 'directions propagation perturbation'], "metadata": {'courseId': 'phys_ch1_waves', 'chapter': 'Ondes mécaniques progressives', 'lesson': 'Propagation, retard et célérité', 'visualStyle': 'pencil', 'resourceRole': 'teacher_sketch', 'paletteId': 'bac-pencil-v1', 'sourceUrl': 'https://www.youtube.com/watch?v=E79tE5gmdrk', 'sourceTeacher': 'Jihad El Goufifa', 'sourceVideoTitle': 'Physique-Chimie 2Bac - 1: Les ondes mécaniques progressives (Cours)', 'auditStatus': 'video_reviewed', 'sourceTimecodes': ['09:30–12:00 · corde transversale', '29:00–32:00 · ressort et compression longitudinale'], 'learningObjectives': ['Comparer direction de propagation et direction du mouvement local', 'Classer une onde mécanique'], 'llmIntents': ['comparer onde transversale et longitudinale', 'dessiner corde et ressort avec les directions'], 'drawingSteps': ['Séparer le tableau en deux', 'Tracer la corde et l’impulsion', 'Tracer le ressort et une compression', 'Ajouter les deux paires de flèches']}},
    {"id": 'phys_croquis_son_milieu', "title": 'Croquis au crayon — Le son a besoin d’un milieu', "subject": 'physics', "keywords": ['son milieu matériel', 'cloche à vide', 'son dans le vide', 'diapason bille', 'onde sonore'], "metadata": {'courseId': 'phys_ch1_waves', 'chapter': 'Ondes mécaniques progressives', 'lesson': 'Propagation, retard et célérité', 'visualStyle': 'pencil', 'resourceRole': 'teacher_sketch', 'paletteId': 'bac-pencil-v1', 'sourceUrl': 'https://www.youtube.com/watch?v=E79tE5gmdrk', 'sourceTeacher': 'Jihad El Goufifa', 'sourceVideoTitle': 'Physique-Chimie 2Bac - 1: Les ondes mécaniques progressives (Cours)', 'auditStatus': 'video_reviewed', 'sourceTimecodes': ['18:00–22:00 · sonnette sous cloche et diapason avec bille'], 'learningObjectives': ['Établir que le son est une onde mécanique', 'Relier vibration de la source et mise en mouvement du milieu'], 'llmIntents': ['dessiner l’expérience de la cloche à vide', 'dessiner le diapason et la bille'], 'drawingSteps': ['Tracer la cloche et la sonnette', 'Représenter l’air puis son retrait', 'Tracer le diapason et la bille', 'Conclure que le son exige un milieu matériel']}},
    {"id": 'phys_croquis_superposition', "title": 'Croquis au crayon — Superposition de deux perturbations', "subject": 'physics', "keywords": ['superposition ondes', 'deux perturbations se croisent', 'interférence impulsions', 'ondes après croisement'], "metadata": {'courseId': 'phys_ch1_waves', 'chapter': 'Ondes mécaniques progressives', 'lesson': 'Propagation, retard et célérité', 'visualStyle': 'pencil', 'resourceRole': 'teacher_sketch', 'paletteId': 'bac-pencil-v1', 'sourceUrl': 'https://www.youtube.com/watch?v=E79tE5gmdrk', 'sourceTeacher': 'Jihad El Goufifa', 'sourceVideoTitle': 'Physique-Chimie 2Bac - 1: Les ondes mécaniques progressives (Cours)', 'auditStatus': 'video_reviewed', 'sourceTimecodes': ['23:30–27:00 · approche, superposition puis séparation de deux impulsions'], 'learningObjectives': ['Appliquer le principe de superposition', 'Montrer que les perturbations poursuivent leur propagation après le croisement'], 'llmIntents': ['dessiner deux impulsions qui se croisent', 'expliquer la superposition algébrique'], 'drawingSteps': ['Tracer trois lignes temporelles', 'Dessiner les impulsions avant le croisement', 'Additionner les déformations au croisement', 'Replacer les impulsions après le croisement']}},
    {"id": 'phys_croquis_ressort_celerite', "title": 'Croquis au crayon — Mesurer la célérité sur un ressort', "subject": 'physics', "keywords": ['ressort célérité', 'onde sur ressort', 'capteurs retard distance', 'mesure vitesse propagation', 'compression ressort'], "metadata": {'courseId': 'phys_ch1_waves', 'chapter': 'Ondes mécaniques progressives', 'lesson': 'Propagation, retard et célérité', 'visualStyle': 'pencil', 'resourceRole': 'teacher_sketch', 'paletteId': 'bac-pencil-v1', 'sourceUrl': 'https://www.youtube.com/watch?v=E79tE5gmdrk', 'sourceTeacher': 'Jihad El Goufifa', 'sourceVideoTitle': 'Physique-Chimie 2Bac - 1: Les ondes mécaniques progressives (Cours)', 'auditStatus': 'video_reviewed', 'sourceTimecodes': ['29:00–33:00 · ressort, règle et chronométrage de la propagation'], 'learningObjectives': ['Relier distance, retard et célérité', 'Identifier les grandeurs à mesurer expérimentalement'], 'llmIntents': ['dessiner le montage de mesure sur ressort', 'expliquer v égale d sur tau'], 'drawingSteps': ['Tracer le ressort horizontal', 'Placer A et B', 'Coter la distance d', 'Ajouter les dates et calculer le retard']}},
    {"id": 'phys_croquis_corde_poulie', "title": 'Croquis au crayon — Corde tendue par une masse', "subject": 'physics', "keywords": ['corde poulie masse', 'tension corde', 'célérité tension masse linéique', 'v racine T sur mu', 'poids Mg'], "metadata": {'courseId': 'phys_ch1_waves', 'chapter': 'Ondes mécaniques progressives', 'lesson': 'Propagation, retard et célérité', 'visualStyle': 'pencil', 'resourceRole': 'teacher_sketch', 'paletteId': 'bac-pencil-v1', 'sourceUrl': 'https://www.youtube.com/watch?v=E79tE5gmdrk', 'sourceTeacher': 'Jihad El Goufifa', 'sourceVideoTitle': 'Physique-Chimie 2Bac - 1: Les ondes mécaniques progressives (Cours)', 'auditStatus': 'video_reviewed', 'sourceTimecodes': ['44:00–51:00 · corde de longueur L, poulie, masse et bilan des forces'], 'learningObjectives': ['Relier la célérité à la tension et à la masse linéique', 'Déduire la tension du poids de la masse suspendue'], 'llmIntents': ['dessiner corde poulie masse suspendue', 'expliquer l’effet de la tension sur la célérité'], 'drawingSteps': ['Tracer la corde et la poulie', 'Suspendre la masse M', 'Ajouter T et P', 'Écrire T voisin de Mg puis v égale racine de T sur mu']}},
    {"id": 'phys_croquis_retard', "title": 'Croquis au crayon — Retard entre la source S et le point M', "subject": 'physics', "keywords": ['retard onde source point M', 'tau SM sur v', 'élongation yM yS', 'onde progressive relation temporelle'], "metadata": {'courseId': 'phys_ch1_waves', 'chapter': 'Ondes mécaniques progressives', 'lesson': 'Propagation, retard et célérité', 'visualStyle': 'pencil', 'resourceRole': 'teacher_sketch', 'paletteId': 'bac-pencil-v1', 'sourceUrl': 'https://www.youtube.com/watch?v=E79tE5gmdrk', 'sourceTeacher': 'Jihad El Goufifa', 'sourceVideoTitle': 'Physique-Chimie 2Bac - 1: Les ondes mécaniques progressives (Cours)', 'auditStatus': 'video_reviewed', 'sourceTimecodes': ['56:00–58:20 · source S, point M, distance et retard temporel'], 'learningObjectives': ['Interpréter le retard comme une translation temporelle', 'Écrire τ égale SM sur v et yM de t égale yS de t moins τ'], 'llmIntents': ['dessiner le retard entre S et M', 'expliquer la relation yM(t)=yS(t−tau)'], 'drawingSteps': ['Tracer le milieu avec S et M', 'Coter SM', 'Dessiner le profil à la source puis au point M', 'Écrire les deux relations de retard']}},
    {"id": 'phys_croquis_deux_capteurs', "title": 'Croquis au crayon — Deux capteurs sur une corde', "subject": 'physics', "keywords": ['deux capteurs onde', 'capteurs A B corde', 'distance retard célérité', 'AB 80 cm 20 ms', 'protocole onde'], "metadata": {'courseId': 'phys_ch1_waves', 'chapter': 'Ondes mécaniques progressives', 'lesson': 'Retard et célérité — mesurer sans confondre', 'visualStyle': 'pencil', 'resourceRole': 'teacher_sketch', 'paletteId': 'bac-pencil-v1', 'auditStatus': 'curriculum_reviewed', 'learningObjectives': ['Identifier d, tA et tB dans un montage', 'Convertir les unités avant le calcul de v'], 'llmIntents': ['dessiner deux capteurs sur une corde', 'poser un calcul de célérité à partir de AB et du retard'], 'drawingSteps': ['Tracer la corde et la source', 'Placer A et B', 'Coter AB', 'Noter tA et tB', 'Écrire τ puis v avec conversions']}},
    {"id": 'phys_croquis_signaux_retard', "title": 'Croquis au crayon — Décalage de deux signaux', "subject": 'physics', "keywords": ['signaux capteurs A B', 'signaux homologues', 'pics décalés retard', 'retard graphique', 'lecture graphique retard', 'points homologues', 'tA 1,5 tB 3,5'], "metadata": {'courseId': 'phys_ch1_waves', 'chapter': 'Ondes mécaniques progressives', 'lesson': 'Méthode BAC — exploiter deux signaux', 'visualStyle': 'pencil', 'resourceRole': 'teacher_sketch', 'paletteId': 'bac-pencil-v1', 'auditStatus': 'curriculum_reviewed', 'learningObjectives': ['Repérer deux points homologues sur des signaux', 'Lire τ puis calculer la célérité'], 'llmIntents': ['dessiner deux pics décalés', 'montrer comment lire un retard sur un graphe'], 'drawingSteps': ['Tracer les axes', 'Dessiner le signal A', 'Reproduire la même forme décalée pour B', 'Projeter les pics sur t', 'Coter τ']}},
    {"id": 'phys_croquis_bilan_ondes', "title": 'Croquis au crayon — Bilan des ondes mécaniques', "subject": 'physics', "keywords": ['bilan ondes mécaniques', 'carte onde propagation retard célérité', 'milieu énergie transversale longitudinale', 'synthèse chapitre ondes'], "metadata": {'courseId': 'phys_ch1_waves', 'chapter': 'Ondes mécaniques progressives', 'lesson': 'Bilan de compétence', 'visualStyle': 'pencil', 'resourceRole': 'teacher_sketch', 'paletteId': 'bac-pencil-v1', 'auditStatus': 'curriculum_reviewed', 'learningObjectives': ['Relier définition, types et mesure d’une onde mécanique', 'Mobiliser τ et v avec les unités SI'], 'llmIntents': ['dessiner le bilan du chapitre des ondes', 'faire une carte propagation types retard célérité'], 'drawingSteps': ['Écrire onde mécanique au centre', 'Ajouter milieu et transport d’énergie', 'Ajouter transversale et longitudinale', 'Ajouter τ puis v']}},
    {"id": 'svt_glycolyse', "title": 'La Glycolyse — Dégradation du glucose', "subject": 'svt', "keywords": ['glycolyse', 'glucose', 'pyruvate', 'atp', 'cytoplasme', 'تحلل سكري', 'التحلل السكري', 'dégradation'], "metadata": {}},
    {"id": 'svt_respiration_cellulaire', "title": "Respiration cellulaire — Vue d'ensemble", "subject": 'svt', "keywords": ['respiration', 'cellulaire', 'aérobie', 'mitochondrie', 'krebs', 'chaîne respiratoire', 'atp', 'oxygène', 'تنفس خلوي', 'السلسلة التنفسية'], "metadata": {}},
    {"id": 'svt_fermentation', "title": 'Fermentation — Voies anaérobies', "subject": 'svt', "keywords": ['fermentation', 'anaérobie', 'lactique', 'alcoolique', 'éthanol', 'sans oxygène', 'تخمر', 'comparaison'], "metadata": {}},
    {"id": 'svt_muscle_sarcomere', "title": 'Structure du sarcomère', "subject": 'svt', "keywords": ['sarcomère', 'sarcomere', 'muscle', 'strié', 'actine', 'myosine', 'contraction', 'عضلة', 'بنية العضلة'], "metadata": {}},
    {"id": 'svt_adn_structure', "title": "Structure de l'ADN — Double hélice", "subject": 'svt', "keywords": ['adn', 'double hélice', 'nucléotide', 'base azotée', 'watson', 'crick', 'complémentarité', 'الحمض النووي', 'بنية'], "metadata": {}},
    {"id": 'svt_transcription_traduction', "title": 'Expression génétique — Transcription et Traduction', "subject": 'svt', "keywords": ['transcription', 'traduction', 'arnm', 'protéine', 'ribosome', 'codon', 'code génétique', 'codon initiateur', 'codon stop', 'acide aminé', 'استنساخ', 'ترجمة', 'expression'], "metadata": {}},
    {"id": 'svt_mitose', "title": 'La Mitose — Division cellulaire conservatrice', "subject": 'svt', "keywords": ['mitose', 'division', 'prophase', 'métaphase', 'anaphase', 'télophase', 'chromosome', 'انقسام غير مباشر'], "metadata": {}},
    {"id": 'svt_subduction', "title": "Subduction — Plongement d'une plaque océanique", "subject": 'svt', "keywords": ['subduction', 'plaque plongeante', 'plaque océanique', 'fosse', 'volcanisme', 'arc volcanique', 'fusion partielle', 'déshydratation', 'métamorphisme', 'الغوص', 'صفيحة'], "metadata": {}},
    {"id": 'svt_cellule_mitochondrie', "title": 'De la cellule à la mitochondrie', "subject": 'svt', "keywords": ['cellule', 'cellule eucaryote', 'cytoplasme', 'noyau', 'mitochondrie', 'respiration cellulaire', 'خلية', 'الميتوكندري'], "metadata": {}},
    {"id": 'svt_mitochondrie_structure', "title": 'Structure de la Mitochondrie — Ultrastructure', "subject": 'svt', "keywords": ['mitochondrie', 'ultrastructure de la mitochondrie', 'crêtes mitochondriales', 'membrane interne', 'membrane externe', 'crêtes', 'matrice', 'espace intermembranaire', 'الميتوكندري', 'بنية الميتوكندري'], "metadata": {}},
    {"id": 'svt_chaine_respiratoire', "title": 'Chaîne respiratoire et Phosphorylation oxydative', "subject": 'svt', "keywords": ['chaîne respiratoire', 'phosphorylation oxydative', 'atp synthase', 'complexe', 'gradient', 'nadh', 'fadh2', 'السلسلة التنفسية', 'الفسفرة التأكسدية'], "metadata": {}},
    {"id": 'svt_cycle_krebs', "title": 'Cycle de Krebs — Détail des réactions', "subject": 'svt', "keywords": ['krebs', 'cycle', 'acétyl-coa', 'citrate', 'oxaloacétate', 'matrice', 'حلقة كريبس', 'دورة كريبس'], "metadata": {}},
    {"id": 'svt_fibre_musculaire', "title": 'Ultrastructure de la fibre musculaire striée', "subject": 'svt', "keywords": ['fibre musculaire', 'myofibrille', 'réticulum sarcoplasmique', 'tubule t', 'triade', 'ultrastructure', 'الألياف العضلية', 'بنية العضلة'], "metadata": {}},
    {"id": 'svt_bilan_energetique', "title": 'Bilan énergétique — Respiration vs Fermentation', "subject": 'svt', "keywords": ['bilan', 'énergétique', 'rendement', 'comparaison', 'respiration', 'fermentation', 'atp', 'حصيلة طاقية', 'مقارنة'], "metadata": {}},
    {"id": 'svt_dorsale_accretion', "title": 'Dorsale océanique — Accrétion et expansion océanique', "subject": 'svt', "keywords": ['dorsale', 'accrétion', 'expansion océanique', 'expansion des fonds', 'plancher océanique', 'rift', 'basalte', 'gabbro', 'chambre magmatique', 'anomalies magnétiques', 'asthénosphère', 'الظهرة المحيطية', 'التوسع المحيطي'], "metadata": {}},
    {"id": 'svt_metamorphisme', "title": 'Métamorphisme — Faciès et gradients (subduction / collision)', "subject": 'svt', "keywords": ['métamorphisme', 'faciès métamorphique', 'schistes verts', 'schistes bleus', 'éclogite', 'glaucophane', 'grenat', 'jadéite', 'gradient métamorphique', 'pression température', 'التحول', 'التحول الصخري'], "metadata": {}},
    {"id": 'svt_chaine_montagnes', "title": 'Chaîne de montagnes — Collision continentale', "subject": 'svt', "keywords": ['chaîne de montagnes', 'collision', 'collision continentale', 'orogenèse', 'racine crustale', 'nappe de charriage', 'pli', 'faille inverse', 'ophiolite', 'suture', 'moho', 'raccourcissement', 'سلسلة جبلية', 'التصادم القاري'], "metadata": {}},
    {"id": 'svt_cellule_vegetale', "title": 'La cellule végétale et ses organites', "subject": 'svt', "keywords": ['cellule végétale', 'paroi cellulosique', 'paroi', 'vacuole', 'chloroplaste', 'chlorophylle', 'photosynthèse', 'membrane plasmique', 'cytoplasme', 'organite', 'الخلية النباتية', 'الجدار السليلوزي', 'الفجوة'], "metadata": {}},
    {"id": 'svt_croquis_cellule_mitochondrie', "title": 'Croquis au crayon — De la cellule à la mitochondrie', "subject": 'svt', "keywords": ['cellule', 'mitochondrie', 'cellule mitochondrie', 'localisation mitochondrie', 'zoom mitochondrie', 'croquis', 'dessine', 'dessin au tableau', 'schématise', 'rsem lia', 'rassam lia', 'رسم ليا', 'consommation matière organique', 'خلية', 'ميتوكندريا'], "metadata": {'courseId': 'svt_ch1_energy', 'chapter': "Consommation de la matière organique et libération de l'énergie", 'lesson': "Libération de l'énergie emmagasinée dans la matière organique", 'visualStyle': 'pencil', 'resourceRole': 'teacher_sketch', 'learningObjectives': ['Localiser la mitochondrie dans une cellule eucaryote', 'Relier respiration cellulaire et mitochondrie'], 'llmIntents': ['dessiner une cellule avec ses mitochondries', 'faire un zoom cellule-mitochondrie', 'introduire le lieu de la respiration', 'montrer une membrane interne continue formant les crêtes'], 'drawingSteps': ['Tracer la cellule et le noyau', 'Ajouter quelques mitochondries', 'Agrandir une mitochondrie et la relier par une flèche', 'Tracer la membrane interne en un seul trait continu puis former ses replis']}},
    {"id": 'svt_croquis_atp_adp', "title": 'Croquis au crayon — Cycle ATP–ADP', "subject": 'svt', "keywords": ['ATP', 'ADP', 'cycle ATP ADP', 'hydrolyse ATP', 'phosphorylation ADP', 'couplage énergétique', 'croquis', 'dessine', 'dessin au tableau', 'schématise', 'rsem lia', 'rassam lia', 'رسم ليا', 'monnaie énergétique', 'طاقة', 'أدينوزين ثلاثي الفوسفات'], "metadata": {'courseId': 'svt_ch1_energy', 'chapter': "Consommation de la matière organique et libération de l'énergie", 'lesson': "Libération de l'énergie emmagasinée dans la matière organique", 'visualStyle': 'pencil', 'resourceRole': 'teacher_sketch', 'learningObjectives': ['Expliquer l’hydrolyse et la régénération de l’ATP', 'Relier voies cataboliques et activités cellulaires'], 'llmIntents': ['dessiner le cycle ATP-ADP', 'expliquer le couplage énergétique', 'montrer comment ATP est consommé puis régénéré'], 'drawingSteps': ['Écrire ATP et ses trois phosphates', 'Tracer l’hydrolyse vers ADP + Pi', 'Tracer la phosphorylation en sens inverse', 'Relier libération et consommation d’énergie']}},
    {"id": 'svt_croquis_experience_levures', "title": 'Croquis au crayon — Levures avec ou sans dioxygène', "subject": 'svt', "keywords": ['levures', 'expérience levures', 'levures avec sans O2', 'EXAO O2 CO2', 'respiration fermentation expérience', 'croquis', 'dessine', 'dessin au tableau', 'schématise', 'rsem lia', 'rassam lia', 'رسم ليا', 'protocole expérimental', 'خميرة', 'تنفس', 'تخمر'], "metadata": {'courseId': 'svt_ch1_energy', 'chapter': "Consommation de la matière organique et libération de l'énergie", 'lesson': "Libération de l'énergie emmagasinée dans la matière organique", 'visualStyle': 'pencil', 'resourceRole': 'teacher_sketch', 'learningObjectives': ['Comparer respiration et fermentation à partir de mesures', 'Identifier variable, témoins et résultats attendus'], 'llmIntents': ['dessiner le protocole avec des levures', 'comparer une culture avec et sans dioxygène', 'préparer une lecture de courbes EXAO'], 'drawingSteps': ['Tracer deux enceintes identiques avec levures et glucose', 'Indiquer +O₂ et −O₂', 'Ajouter les capteurs et les résultats mesurés']}},
    {"id": 'svt_croquis_glycolyse', "title": 'Croquis au crayon — Bilan de la glycolyse', "subject": 'svt', "keywords": ['glycolyse', 'bilan glycolyse', 'glucose pyruvate', '2 ATP nets', '2 NADH H+', 'cytoplasme', 'croquis', 'dessine', 'dessin au tableau', 'schématise', 'rsem lia', 'rassam lia', 'رسم ليا', 'تحلل سكري'], "metadata": {'courseId': 'svt_ch1_energy', 'chapter': "Consommation de la matière organique et libération de l'énergie", 'lesson': "Libération de l'énergie emmagasinée dans la matière organique", 'visualStyle': 'pencil', 'resourceRole': 'teacher_sketch', 'learningObjectives': ['Établir le bilan carboné et énergétique de la glycolyse', 'Localiser la glycolyse dans le cytoplasme'], 'llmIntents': ['dessiner le bilan de la glycolyse', 'montrer le passage glucose-pyruvate', 'expliquer les 2 ATP nets'], 'drawingSteps': ['Écrire glucose C₆', 'Tracer la phase d’activation et la coupure', 'Dessiner deux pyruvates C₃', 'Ajouter le bilan net ATP et NADH,H⁺']}},
    {"id": 'svt_croquis_mitochondrie', "title": 'Croquis au crayon — Ultrastructure de la mitochondrie', "subject": 'svt', "keywords": ['mitochondrie', 'croquis mitochondrie', 'ultrastructure mitochondrie', 'crêtes mitochondriales', 'membrane interne externe', 'matrice mitochondriale', 'espace intermembranaire', 'dessine', 'dessin au tableau', 'schématise', 'rsem lia', 'rassam lia', 'رسم ليا', 'ميتوكندريا', 'بنية الميتوكندريا'], "metadata": {'courseId': 'svt_ch1_energy', 'chapter': "Consommation de la matière organique et libération de l'énergie", 'lesson': "Libération de l'énergie emmagasinée dans la matière organique", 'visualStyle': 'pencil', 'resourceRole': 'teacher_sketch', 'learningObjectives': ['Identifier les compartiments mitochondriaux', 'Relier structure et étapes de la respiration'], 'llmIntents': ['dessiner une mitochondrie annotée', 'expliquer que les crêtes sont des replis de la membrane interne', 'localiser Krebs et chaîne respiratoire'], 'drawingSteps': ['Tracer la membrane externe', 'Tracer la membrane interne en un seul trait continu autour de la matrice', 'Former plusieurs replis de cette même membrane sur toute la longueur', 'Nommer espace intermembranaire, crêtes et matrice', 'Localiser Krebs et chaîne respiratoire']}},
    {"id": 'svt_croquis_krebs', "title": 'Croquis au crayon — Bilan du cycle de Krebs', "subject": 'svt', "keywords": ['krebs', 'cycle de Krebs', 'bilan cycle Krebs', 'acétyl CoA oxaloacétate', 'matrice mitochondriale', 'NADH FADH2 CO2', 'croquis', 'dessine', 'dessin au tableau', 'schématise', 'rsem lia', 'rassam lia', 'رسم ليا', 'دورة كريبس'], "metadata": {'courseId': 'svt_ch1_energy', 'chapter': "Consommation de la matière organique et libération de l'énergie", 'lesson': "Libération de l'énergie emmagasinée dans la matière organique", 'visualStyle': 'pencil', 'resourceRole': 'teacher_sketch', 'learningObjectives': ['Établir le bilan du cycle de Krebs pour un glucose', 'Montrer le rôle majeur des transporteurs réduits'], 'llmIntents': ['dessiner le cycle de Krebs', 'résumer les entrées et sorties de Krebs', 'expliquer NADH et FADH2 avant la chaîne'], 'drawingSteps': ['Tracer un cycle simple dans la matrice', 'Faire entrer deux acétyl-CoA', 'Faire sortir CO₂, NADH,H⁺, FADH₂ et ATP', 'Préciser deux tours par glucose']}},
    {"id": 'svt_croquis_chaine_respiratoire', "title": 'Croquis au crayon — Chaîne respiratoire et ATP synthase', "subject": 'svt', "keywords": ['chaîne respiratoire', 'croquis chaîne respiratoire', 'phosphorylation oxydative', 'gradient H+', 'ATP synthase', 'dioxygène accepteur final', 'NADH électrons', 'dessine', 'dessin au tableau', 'schématise', 'rsem lia', 'rassam lia', 'رسم ليا', 'السلسلة التنفسية', 'أكسجين'], "metadata": {'courseId': 'svt_ch1_energy', 'chapter': "Consommation de la matière organique et libération de l'énergie", 'lesson': "Libération de l'énergie emmagasinée dans la matière organique", 'visualStyle': 'pencil', 'resourceRole': 'teacher_sketch', 'learningObjectives': ['Distinguer flux d’électrons, pompage de H⁺ et synthèse d’ATP', 'Expliquer le rôle final de O₂'], 'llmIntents': ['dessiner la chaîne respiratoire', 'expliquer le gradient protonique', 'montrer le rôle de ATP synthase et O2'], 'drawingSteps': ['Tracer la membrane interne', 'Placer les complexes et le trajet des électrons', 'Dessiner le pompage des H⁺', 'Ajouter l’ATP synthase et le retour des H⁺']}},
    {"id": 'svt_croquis_respiration_fermentation', "title": 'Croquis au crayon — Respiration ou fermentation', "subject": 'svt', "keywords": ['respiration', 'fermentation', 'respiration versus fermentation', 'avec sans dioxygène', 'pyruvate bifurcation', 'rendement ATP comparé', 'fermentation lactique alcoolique', 'croquis', 'dessine', 'dessin au tableau', 'schématise', 'rsem lia', 'rassam lia', 'رسم ليا', 'تنفس', 'تخمر'], "metadata": {'courseId': 'svt_ch1_energy', 'chapter': "Consommation de la matière organique et libération de l'énergie", 'lesson': "Libération de l'énergie emmagasinée dans la matière organique", 'visualStyle': 'pencil', 'resourceRole': 'teacher_sketch', 'learningObjectives': ['Comparer respiration et fermentation', 'Expliquer l’effet de O₂ sur l’oxydation et le rendement'], 'llmIntents': ['dessiner la bifurcation respiration-fermentation', 'comparer les voies avec et sans O2', 'expliquer pourquoi la respiration produit plus ATP'], 'drawingSteps': ['Tracer la glycolyse commune', 'Faire bifurquer les pyruvates selon la présence de O₂', 'Écrire les produits finaux', 'Comparer les rendements ATP']}},
    {"id": 'svt_croquis_bilan_respiration', "title": 'Croquis au crayon — Bilan de la respiration cellulaire', "subject": 'svt', "keywords": ['respiration cellulaire', 'bilan respiration cellulaire', 'glucose O2 CO2 H2O ATP', 'glycolyse Krebs chaîne respiratoire', 'bilan énergétique global', 'croquis', 'dessine', 'dessin au tableau', 'schématise', 'rsem lia', 'rassam lia', 'رسم ليا', 'libération énergie', 'تنفس خلوي'], "metadata": {'courseId': 'svt_ch1_energy', 'chapter': "Consommation de la matière organique et libération de l'énergie", 'lesson': "Libération de l'énergie emmagasinée dans la matière organique", 'visualStyle': 'pencil', 'resourceRole': 'teacher_sketch', 'learningObjectives': ['Organiser les étapes de la respiration et leurs lieux', 'Construire le bilan global de l’oxydation du glucose'], 'llmIntents': ['dessiner le schéma-bilan de la respiration', 'résumer tout le premier cours', 'relier glycolyse Krebs chaîne et ATP'], 'drawingSteps': ['Écrire le glucose à l’entrée', 'Aligner glycolyse, Krebs et chaîne respiratoire', 'Associer cytoplasme, matrice et membrane interne', 'Ajouter O₂, CO₂, H₂O, ATP et chaleur']}},
]

SCHEMA_IDS: frozenset[str] = frozenset(entry["id"] for entry in SCHEMA_CATALOG)


@lru_cache(maxsize=None)
def _motif(mot: str) -> re.Pattern:
    """Un mot-clé ne compte que s'il est un MOT, pas une suite de lettres.

    Cherché en simple sous-chaîne, `exp` se trouve dans « expansion » et `ln`
    dans une dizaine de mots : un cours sur la dorsale océanique se voyait
    proposer le schéma des fonctions exponentielles. Les bornes règlent le
    problème pour le français comme pour l'arabe, les bornes de mot étant
    unicode.

    Le pluriel reste admis (`s` ou `x` final) : un cours parle des
    « myofibrilles » et des « crêtes », le mot-clé est au singulier, et
    l'exiger à la lettre faisait manquer le bon schéma.
    """
    return re.compile(rf"(?<!\w){re.escape(_sans_accents(mot))}[sx]?(?!\w)", re.UNICODE)


def _sans_accents(texte: str) -> str:
    """Un eleve tape « accretion » : le mot-cle accentue doit quand meme repondre."""
    plie = unicodedata.normalize("NFKD", texte.lower())
    return "".join(c for c in plie if not unicodedata.combining(c))


_MOTS_GENERIQUES = {
    "reaction", "structure", "cycle", "energie", "bilan", "comparaison", "courbe",
    "fonction", "cellule", "muscle", "mouvement", "mecanique", "onde", "oscillation",
    "force", "tableau", "schema", "equilibre", "complexe", "arithmetique", "division",
    # « variation » est un mot-cle de la DERIVATION, et un mot francais partout
    # ailleurs. Seul, il valait deux points : « la variation de la pression
    # arterielle » — une courbe de SVT — se voyait proposer le schema de
    # derivation. Une vraie lecon de derivation dit « derivee » ou
    # « derivation », et garde donc son schema.
    "variation",
}


def _poids_mot_cle(mot: str) -> int:
    """Une notion distinctive seule doit suffire, un mot de chapitre non.

    « mitose », « électrolyse » ou « sarcomère » désignent sans ambiguïté une
    figure et valent deux points. « structure » ou « énergie » restent à un
    point pour ne jamais imposer un schéma sur une simple coïncidence.
    """
    normalise = _sans_accents(mot.strip())
    if " " in normalise:
        return 3
    if len(normalise) >= 6 and normalise not in _MOTS_GENERIQUES:
        return 2
    return 1


def match_schema(context: str) -> tuple[str | None, int]:
    """Le schéma de la bibliothèque qui colle le mieux au contexte, et son score.

    Un mot-clé en PLUSIEURS mots pèse double : « fibre musculaire » désigne un
    schéma, « muscle » désigne un chapitre entier. Sans cette pondération, un
    cours sur la fibre musculaire se voyait proposer le sarcomère, les deux
    étant à égalité sur des mots génériques.

    Les appelants décident du seuil : rapprocher n'est pas afficher.
    """
    contexte = _sans_accents(context or "")
    if not contexte.strip():
        return None, 0

    meilleur_id, meilleur_score, meilleur_precision = None, 0, 0
    for entry in SCHEMA_CATALOG:
        trouves = [mot for mot in entry["keywords"] if _motif(mot).search(contexte)]
        if not trouves:
            continue
        score = sum(_poids_mot_cle(mot) for mot in trouves)
        # À score égal, le mot-clé le plus long tranche : « fibre musculaire »
        # l'emporte sur « muscle », qui désigne le chapitre et non la figure.
        precision = max(len(mot) for mot in trouves)
        if (score, precision) > (meilleur_score, meilleur_precision):
            meilleur_id, meilleur_score, meilleur_precision = entry["id"], score, precision
    return (meilleur_id, meilleur_score) if meilleur_score else (None, 0)


def schema_title(schema_id: str) -> str:
    for entry in SCHEMA_CATALOG:
        if entry["id"] == schema_id:
            return entry["title"]
    return ""


SCHEMA_CATALOG_PROMPT = """[SCHÉMAS SVG DISPONIBLES — 69 identifiants]
Ces schémas sont déjà dessinés, animés et annotés. Les afficher coûte moins
cher et rend mieux qu'un dessin improvisé : si l'un d'eux couvre la notion,
c'est LUI qu'on affiche, dans TOUS les modes (cours, exercice, examen,
question libre).
Les ressources marquées CROQUIS CRAYON LIVE BOARD sont les versions simples
qu'un professeur peut tracer au tableau. Si l'élève dit « dessine »,
« croquis », « schématise » ou « au tableau », préfère la version CROQUIS de
la notion ; pour une consultation détaillée sans demande de dessin, garde le
schéma de référence.
Format : <schema>identifiant</schema> — ou l'action `show_schema`.
N'INVENTE JAMAIS un identifiant : s'il n'est pas dans cette liste, il n'existe
pas, et l'élève ne voit rien.

  SVT :
    svt_glycolyse — La Glycolyse — Dégradation du glucose
    svt_respiration_cellulaire — Respiration cellulaire — Vue d'ensemble
    svt_fermentation — Fermentation — Voies anaérobies
    svt_muscle_sarcomere — Structure du sarcomère
    svt_adn_structure — Structure de l'ADN — Double hélice
    svt_transcription_traduction — Expression génétique — Transcription et Traduction
    svt_mitose — La Mitose — Division cellulaire conservatrice
    svt_subduction — Subduction — Plongement d'une plaque océanique
    svt_cellule_mitochondrie — De la cellule à la mitochondrie
    svt_mitochondrie_structure — Structure de la Mitochondrie — Ultrastructure
    svt_chaine_respiratoire — Chaîne respiratoire et Phosphorylation oxydative
    svt_cycle_krebs — Cycle de Krebs — Détail des réactions
    svt_fibre_musculaire — Ultrastructure de la fibre musculaire striée
    svt_bilan_energetique — Bilan énergétique — Respiration vs Fermentation
    svt_dorsale_accretion — Dorsale océanique — Accrétion et expansion océanique
    svt_metamorphisme — Métamorphisme — Faciès et gradients (subduction / collision)
    svt_chaine_montagnes — Chaîne de montagnes — Collision continentale
    svt_cellule_vegetale — La cellule végétale et ses organites
    svt_croquis_cellule_mitochondrie — Croquis au crayon — De la cellule à la mitochondrie [CROQUIS CRAYON LIVE BOARD — dessiner une cellule avec ses mitochondries; faire un zoom cellule-mitochondrie]
    svt_croquis_atp_adp — Croquis au crayon — Cycle ATP–ADP [CROQUIS CRAYON LIVE BOARD — dessiner le cycle ATP-ADP; expliquer le couplage énergétique]
    svt_croquis_experience_levures — Croquis au crayon — Levures avec ou sans dioxygène [CROQUIS CRAYON LIVE BOARD — dessiner le protocole avec des levures; comparer une culture avec et sans dioxygène]
    svt_croquis_glycolyse — Croquis au crayon — Bilan de la glycolyse [CROQUIS CRAYON LIVE BOARD — dessiner le bilan de la glycolyse; montrer le passage glucose-pyruvate]
    svt_croquis_mitochondrie — Croquis au crayon — Ultrastructure de la mitochondrie [CROQUIS CRAYON LIVE BOARD — dessiner une mitochondrie annotée; expliquer que les crêtes sont des replis de la membrane interne]
    svt_croquis_krebs — Croquis au crayon — Bilan du cycle de Krebs [CROQUIS CRAYON LIVE BOARD — dessiner le cycle de Krebs; résumer les entrées et sorties de Krebs]
    svt_croquis_chaine_respiratoire — Croquis au crayon — Chaîne respiratoire et ATP synthase [CROQUIS CRAYON LIVE BOARD — dessiner la chaîne respiratoire; expliquer le gradient protonique]
    svt_croquis_respiration_fermentation — Croquis au crayon — Respiration ou fermentation [CROQUIS CRAYON LIVE BOARD — dessiner la bifurcation respiration-fermentation; comparer les voies avec et sans O2]
    svt_croquis_bilan_respiration — Croquis au crayon — Bilan de la respiration cellulaire [CROQUIS CRAYON LIVE BOARD — dessiner le schéma-bilan de la respiration; résumer tout le premier cours]
  PHYSIQUE :
    phys_ondes_mecaniques — Ondes mécaniques progressives — propagation et retard
    phys_dipole_rc — Dipôle RC — Charge et décharge
    phys_rlc — Oscillations RLC série
    phys_newton — Les trois lois de Newton
    phys_croquis_propagation_locale — Croquis au crayon — Propagation et mouvement local [CROQUIS CRAYON LIVE BOARD — dessiner une impulsion qui se propage; expliquer ce qui bouge dans une onde mécanique]
    phys_croquis_transversale_longitudinale — Croquis au crayon — Onde transversale ou longitudinale [CROQUIS CRAYON LIVE BOARD — comparer onde transversale et longitudinale; dessiner corde et ressort avec les directions]
    phys_croquis_son_milieu — Croquis au crayon — Le son a besoin d’un milieu [CROQUIS CRAYON LIVE BOARD — dessiner l’expérience de la cloche à vide; dessiner le diapason et la bille]
    phys_croquis_superposition — Croquis au crayon — Superposition de deux perturbations [CROQUIS CRAYON LIVE BOARD — dessiner deux impulsions qui se croisent; expliquer la superposition algébrique]
    phys_croquis_ressort_celerite — Croquis au crayon — Mesurer la célérité sur un ressort [CROQUIS CRAYON LIVE BOARD — dessiner le montage de mesure sur ressort; expliquer v égale d sur tau]
    phys_croquis_corde_poulie — Croquis au crayon — Corde tendue par une masse [CROQUIS CRAYON LIVE BOARD — dessiner corde poulie masse suspendue; expliquer l’effet de la tension sur la célérité]
    phys_croquis_retard — Croquis au crayon — Retard entre la source S et le point M [CROQUIS CRAYON LIVE BOARD — dessiner le retard entre S et M; expliquer la relation yM(t)=yS(t−tau)]
    phys_croquis_deux_capteurs — Croquis au crayon — Deux capteurs sur une corde [CROQUIS CRAYON LIVE BOARD — dessiner deux capteurs sur une corde; poser un calcul de célérité à partir de AB et du retard]
    phys_croquis_signaux_retard — Croquis au crayon — Décalage de deux signaux [CROQUIS CRAYON LIVE BOARD — dessiner deux pics décalés; montrer comment lire un retard sur un graphe]
    phys_croquis_bilan_ondes — Croquis au crayon — Bilan des ondes mécaniques [CROQUIS CRAYON LIVE BOARD — dessiner le bilan du chapitre des ondes; faire une carte propagation types retard célérité]
  CHIMIE :
    chem_cinetique — Transformations lentes et rapides — facteurs cinétiques
    chem_radioactivite — Radioactivité — Décroissance radioactive
    chem_acides_bases — Acides et bases — Équilibres en solution aqueuse
    chem_piles_electrolyse — Piles électrochimiques et électrolyse
    chem_esterification — Estérification et hydrolyse
    chem_croquis_carte_cinetique — Croquis au crayon — Carte des transformations rapides et lentes [CROQUIS CRAYON LIVE BOARD — dessiner la carte rapide lente; résumer les facteurs cinétiques du cours]
    chem_croquis_transfert_electrons — Croquis au crayon — Transfert d’électrons en oxydoréduction [CROQUIS CRAYON LIVE BOARD — dessiner le transfert d’électrons; rappeler oxydant et réducteur avant la cinétique]
    chem_croquis_duree_transformation — Croquis au crayon — Durée d’une transformation chimique [CROQUIS CRAYON LIVE BOARD — dessiner une courbe cinétique vers un plateau; expliquer la durée delta t]
    chem_croquis_facteurs_controles — Croquis au crayon — Comparer concentration et température [CROQUIS CRAYON LIVE BOARD — dessiner deux béchers pour comparer la température; dessiner une expérience sur la concentration]
    chem_croquis_trois_bechers — Croquis au crayon — Trois béchers à températures différentes [CROQUIS CRAYON LIVE BOARD — dessiner trois béchers froid tempéré chaud; faire prédire l’intensité du dégagement gazeux]
    chem_croquis_indices_macroscopiques — Croquis au crayon — Indices macroscopiques d’une transformation [CROQUIS CRAYON LIVE BOARD — dessiner les indices d’une transformation chimique; choisir entre couleur gaz pH et conductivité]
    chem_croquis_quatre_facteurs — Croquis au crayon — Les quatre facteurs cinétiques [CROQUIS CRAYON LIVE BOARD — dessiner les quatre facteurs cinétiques; expliquer chocs fréquents surface et catalyse]
    chem_croquis_catalyseur — Croquis au crayon — Ce que change un catalyseur [CROQUIS CRAYON LIVE BOARD — dessiner le profil énergétique avec et sans catalyseur; expliquer catalyseur régénéré et même quantité finale]
    chem_croquis_surface_contact — Croquis au crayon — Comprimé entier ou réduit en poudre [CROQUIS CRAYON LIVE BOARD — dessiner comprimé entier contre poudre; expliquer l’effet de la surface de contact]
    chem_croquis_courbes_facteur — Croquis au crayon — Deux cinétiques, même état final [CROQUIS CRAYON LIVE BOARD — dessiner deux courbes rapide et lente; expliquer même état final mais durées différentes]
  MATHS :
    math_limites — Limites et continuité — méthodes du BAC
    math_derivation — Dérivation — Tableau de dérivées et applications
    math_exp_ln — Fonctions exponentielle et logarithme
    math_suites — Suites numériques — Arithmétiques et géométriques
    math_integrales — Intégration — Primitives et calcul d'aires
    math_probabilites — Probabilités — Lois et dénombrement
    math_croquis_formes_indeterminees — Croquis au crayon — Les quatre formes indéterminées [CROQUIS CRAYON LIVE BOARD — dessiner la carte des formes indéterminées; rappeler les quatre FI en limites]
    math_croquis_boite_factorisation — Croquis au crayon — Boîte à outils de factorisation [CROQUIS CRAYON LIVE BOARD — dessiner la boîte des identités remarquables; montrer les factorisations utiles pour une limite]
    math_croquis_strategie_fi — Croquis au crayon — Stratégie pour lever 0/0 [CROQUIS CRAYON LIVE BOARD — dessiner l’algorithme pour lever zéro sur zéro; résoudre graphiquement la méthode factoriser simplifier remplacer]
    math_croquis_trou_limite — Croquis au crayon — Un trou, mais une limite finie [CROQUIS CRAYON LIVE BOARD — dessiner une droite avec un trou; expliquer pourquoi la limite existe même si f de a n’existe pas]
    math_croquis_asymptotes — Croquis au crayon — Asymptotes verticale et horizontale [CROQUIS CRAYON LIVE BOARD — dessiner asymptote verticale et horizontale; expliquer x égale a contre y égale L]
    math_croquis_tvi — Croquis au crayon — Théorème des valeurs intermédiaires [CROQUIS CRAYON LIVE BOARD — dessiner le TVI avec changement de signe; expliquer existence puis unicité d’une racine]
    math_croquis_carte_methodes — Croquis au crayon — Carte des méthodes de limites [CROQUIS CRAYON LIVE BOARD — dessiner la carte complète du chapitre limites; choisir entre factoriser conjugué dominant asymptote et TVI]
"""
