-- Superseded: never disable RLS to fix registration.
-- Deploy the server-only database client first, then apply:
-- database/migrations/20260909_close_public_data_access.sql
-- Account creation is performed by authenticated administrators only.
